<h1>Liste des produits</h1>

<?php $this->add('breadcrumbs'); ?>
<div style="margin: 5px;">
    <a style="" class="btn btn-small btn-success btn-crea" href="back/page/display.html?id_gabarit=<?php echo $this->confVel->get('gabarit', 'idProduit') ?>">
        Ajouter un produit
    </a>
</div>
<div style="clear: both"></div>
<?php echo $this->datatableRender; ?>

<style>
    a.btn {color:rgb(230, 230, 230) !important}
</style>

