<?php
    /** Si le tableau de board est activé */
    if ($this->appConfig->get('board', 'active')) {
        if ($this->controller == 'back/board') {
?>
                                    <li class="gradient-blue text-light-white"><a href="back/board/start.html">Tableau de bord</a></li>
<?php
        } else {
?>
                                    <li><a href="back/board/start.html">Tableau de bord</a></li>
<?php
        }
?>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
<?php
    }
?>
                                    <li class="dropdown<?php echo $this->controller == "back/page" ? ' gradient-blue text-light-white' : ''; ?>">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Catalogue <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li class="<?php ?>"><a href="back/page/liste.html?c=102">Rubriques</a></li>
                                            <li class="<?php ?>"><a href="back/produits/start.html">Produits</a></li>
                                            <li><a href="back/dashboard/start.html?name=criterelibre">Critères libres</a></li>
                                            <li><a href="back/dashboard/start.html?name=critere">Critères à liste</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                    <li class="dropdown<?php echo $this->controller == "back/commande" ? ' gradient-blue text-light-white' : ''; ?>">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Commande <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li class="<?php ?>"><a href="back/commande/encours.html"> En cours (<?php echo $this->countCmd; ?>)</a></li>
                                            <li class="<?php ?>"><a href="back/commande/traite.html"> Traités</a></li>
                                            <li class="<?php ?>"><a href="back/page/liste.html?"> Stats</a></li>
                                        </ul>
                                    </li>

                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                    <li<?php echo $this->controller == "back/media" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="back/dashboard/start.html?name=client">Clients</a></li>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                    <li class="dropdown<?php echo $this->controller == "back/parametre" ? ' gradient-blue text-light-white' : ''; ?>">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Paramètres <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li class="<?php ?>"><a href="back/dashboard/start.html?name=region">Taxes</a></li>
                                            <li class="<?php ?>"><a href="back/page/liste.html?">Port</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
<?php

$this->add('menuadd-2');

?>