<article>
    <h1>Créer mon compte</h1>

    <form class="inscription" action="compte/enregistrement.html" method="post">


    <span class="oblig">Les champs marqués d'une * (étoile) sont obligatoires </span>

        <div class="line">
            <label for="civilite">Civilité</label>
            <select style="width:56px;" name="civilite" id="civilite">
                <option value="M">M</option>
                <option value="Mme">Mme</option>
            </select>
        </div>
        <div class="line">
            <label for="nom">Nom *</label>
            <input type="text" name="nom" id="nom" value="<?php if (isset($this->data['nom'])) echo $this->data['nom']; ?>" />
        </div>
        <div class="line">
            <label for="prenom">Prénom *</label>
            <input type="text" name="prenom" id="prenom" value="<?php if (isset($this->data['prenom'])) echo $this->data['prenom']; ?>" />
        </div>
        <div class="line">
            <label for="mail">Adresse e-mail *</label>
            <input type="text" name="email" id="mail" value="<?php if (isset($this->data['email'])) echo $this->data['email']; ?>" />
        </div>
        <div class="line">
            <label for="password">Mot de passe *</label>
            <input type="password" name="password" id="password" value="" />
        </div>
        <div class="line">
            <label for="confirmpassword">Confirmation *</label>
            <input type="password" name="confirmpassword" id="confirmpassword" value="" />
        </div>
        <div class="line">
            <label for="tel">Téléphone *</label>
            <input type="text" name="tel" id="tel" value="" length="10" />
        </div>
        <div class="line">
            <label for="tel">Téléphone Secondaire</label>
            <input type="text" name="tel2" id="tel2" value="" length="10" />
        </div>
        <div class="line">
            <label for="adresse1">Adresse 1 *</label>
            <input type="text" name="adresse1" id="adresse1" value="" />
        </div>
        <div class="line">
            <label for="adresse2">Adresse 2</label>
            <input type="text" name="adresse2" id="adresse2" value="" />
        </div>
        <div class="line">
            <label for="cp">Code Postal *</label>
            <input type="text" name="cp" id="cp" value="" length="5" />
        </div>
        <div class="line">
            <label for="ville">Ville *</label>
            <input type="text" name="ville" id="ville" value="" />
        </div>
        <div class="line">
            <label> J'accepte les <a href="cgu.html">conditions d'utilisation</a> *</label>
			<input type="checkbox" name="cgu"  style="width:20px;"/>
        </div>
        <div style="clear:both;"></div>
        <div class="linesubmit">
            <input  type="submit" value="Enregistrer"/>
        </div>
    </form>
    <div style="clear:both;"></div>
</article>


