
        <fieldset>
            <legend><?php echo $this->gabarit->getLabel(); ?></legend>

            <div style="display:none;" class="sort-box">
                <div style="background-color: white; padding: 0px 5px; font-size: 11px; display: block; margin-top: -25px;" class="expand-collapse fr"><a style="font-size:11px" href="#" class="expand disabled">Tout déplier</a> / <a style="font-size:11px" href="#" class="collapse">Tout replier</a></div>

                <fieldset>
                    <legend>Filtres</legend>
<?php
    $value = $this->values[0];
    if (count($value['filtres']) > 0) {
        foreach ($value['filtres'] as $filtreId => $options) {
            $filtreShow = $options[0]['actif'];
            $libre      = $options[0]['libre'];
            $filtreName = $options[0]['filtre_name'];
?>
                    <div class="line">
                        <label for="filtre_<?php echo $filtreId . '_' . $this->versionId; ?>"><?php echo $filtreName; ?></label>
                        <input class="filtre-select" type="checkbox" id="filtre_<?php echo $filtreId . '_' . $this->versionId; ?>" name="filtre[]" value="<?php echo $filtreId; ?>"<?php if ($filtreShow) { echo ' checked="checked"'; } ?> />
                    </div>
<?php
        }
    }
?>
                </fieldset>
<?php
    foreach ($this->values as $value) {
        $this->_buildChamps($value);
?>
                <fieldset class="sort-elmt">
                    <legend><?php echo $this->valueLabel; ?></legend>

                    <div>
                        <div class="line">
                            <label for="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>">Visible</label>
                            <input type="checkbox" id="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>" class="changevisible"<?php echo (isset($value['visible']) && $value['visible'] ? ' checked="checked"' : '') ?> />
                            <input type="hidden" value="<?php echo (isset($value['visible']) && $value['visible'] ? 1 : 0) ?>" name="visible[]" />
                        </div>

                        <div class="bloc-field-content<?php if (!isset($value['visible']) || !$value['visible']) { echo ' translucide'; } ?>">
                            <input type="hidden" name="id_<?php echo $this->gabarit->getTable() . '[]" value="' . (isset($value['id']) ? $value['id'] : '') ?>" />

<?php
        echo $this->champsHTML;

        foreach ($value['filtres'] as $filtreId => $options) {
            $filtreShow = $options[0]['actif'];
            $libre      = $options[0]['libre'];
            $filtreName = $options[0]['filtre_name'];
?>
                            <div class="line filtre-content_<?php echo $filtreId; ?>"<?php if (!$filtreShow) { echo ' style="display:none;"'; } ?>>
                                <div class="clearin"></div>
<?php
            if ($libre > 0) {
                $option = $options[0];
                $val  = '';
                if (isset($option['value'])) {
                    $val  = $option['value'];
                }
?>
                                <h4 style="text-align:center; color:#A1A1A1;"><?php echo $filtreName; ?></h4>

                                <div class="line">
                                    <label for="option_<?php echo $option['id'] . '_' . $value['id'] . '_' . $this->versionId; ?>"></label>
                                    <input id="option_<?php echo $option['id'] . '_' . $value['id'] . '_' . $this->versionId; ?>" type="text" name="option[<?php echo $filtreId; ?>][<?php echo $option['id']; ?>][]" value="<?php echo $val; ?>" />
                                </div>
<?php
            } else {
?>
                                <h4 style="text-align:center; color:#A1A1A1;"><?php echo $filtreName; ?></h4>
<?php
                foreach ($options as $option) {
                    $checked = '';
                    $val     = 0;
                    if (isset($option['value'])) {
                        $checked = ' checked="checked"';
                        $val     = 1;
                    }
?>
                                <div class="line">
                                    <label for="option_<?php echo $option['id'] . '_' . $value['id'] . '_' . $this->versionId; ?>"><?php echo $option['name']; ?></label>
                                    <input type="checkbox" class="js-checkbox" id="option_<?php echo $option['id'] . '_' . $value['id'] . '_' . $this->versionId; ?>"<?php echo $checked; ?> />
                                    <input type="hidden" name="option[<?php echo $filtreId; ?>][<?php echo $option['id']; ?>][]" value="<?php echo $val; ?>" />
                                </div>
<?php
                }
            }
?>
                            </div>
<?php
        }
?>
                        </div>
                    </div>

                    <div style="clear:both;">
                        <div class="btn-a gradient-blue fr">
                            <a href="#" class="delBloc<?php echo ( count($this->values) > 1 ? '' : ' translucide' ) ?>">
                                <img src="img/back/white/trash_stroke_16x16.png" border="0" alt="supprimer"/>
                            </a>
                        </div>

                        <div class="btn-a gradient-blue">
                            <a href="#" class="sort-move">
                                <img src="img/back/deplacer.png" alt="Déplacer" />
                            </a>
                        </div>
                    </div>
                </fieldset>
<?php
    }
?>
                <div class="buttonright"><div class="btn-a gradient-blue"><a class="addBloc" href="#">Ajouter un bloc</a></div></div>
            </div>
        </fieldset>

        <script type="text/javascript">
$(function(){
    $('.filtre-select').click(function(){
        var filtreId = $(this).val();
        if ($(this).is(':checked')) {
            $('.filtre-content_' + filtreId).slideDown(500);
        } else {
            $('.filtre-content_' + filtreId).slideUp(500);
        }
    });
});
        </script>

